### ISSUE TITLE
TypeError: TranscriptSeqRiboEmb.__init__() missing 2 required positional arguments: 'use_seq' and 'use_ribo'

### ISSUE THREAD

**Issue by Linesandvad** [TRISTAN-ORF/TIS_transformer#1]
Hi, 

I am trying to get TIS Transformer up and running to be able to make predictions on some transcripts. I have followed the installation guide and succesfully installed the package using pip install transcript-transformer. I have downloaded the required models and example_data.fa in the paths specified below, and I tried running both of the following commands from the example in the user guide:

transcript_transformer predict AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGGT RNA models/proteome/TIS_transformer_L_1.ckpt
transcript_transformer predict data/example_data.fa fa models/proteome/TIS_transformer_L_2.ckpt

For both cases, I get the following error:
TypeError: TranscriptSeqRiboEmb.__init__() missing 2 required positional arguments: 'use_seq' and 'use_ribo'

Can you help me understand why I get this error? 

Thank you very much in advance,
Line

**Comment by jdcla** [comment]
Hello Line,
Thank you for your interest in my research and pointing out this problem. I am in the middle of doing a lot of changes to the transcript-transformer package and it seems I indeed broke this functionality. 

I'll get it fixed today, and give you an update.
Note that you can use https://jdcla.ugent.be/TIS_Transformer_Tool as well. FYI: I don't keep any of the submitted sequences.

**Comment by Linesandvad** [comment]
Thank you for your quick reply. Thank you for pointing out that I can also use your tool - it looks very cool! 
However, I need to run it for a lot of sequences, so I prefer downloading it. Will you let me know when it has been fixed?

**Comment by jdcla** [comment]
This should be fixed now, make sure to update your transcript-transformer package and download the updated models in `/models/proteome`.

 please close the issue if all is in order!
 
 edit: make sure to get v0.5.1

**Comment by Linesandvad** [comment]
Thank you!
